<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.

 * SuiteCRM is an extension to SugarCRM Community Edition developed by Salesagility Ltd.
 * Copyright (C) 2011 - 2014 Salesagility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for  technical reasons, the Appropriate Legal Notices must
 * display the words  "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 ********************************************************************************/


// THIS CONTENT IS GENERATED BY MBPackage.php
$manifest = array (
  0 => 
  array (
    'acceptable_sugar_versions' => 
    array (
      0 => '',
    ),
  ),
  1 => 
  array (
    'acceptable_sugar_flavors' => 
    array (
      0 => 'CE',
      1 => 'PRO',
      2 => 'ENT',
    ),
  ),
  'readme' => '',
  'key' => 'legal',
  'author' => 'Greg',
  'description' => '',
  'icon' => '',
  'is_uninstallable' => true,
  'name' => 'LegalSupport',
  'published_date' => '2014-12-12 02:41:41',
  'type' => 'module',
  'version' => 1418352101,
  'remove_tables' => 'prompt',
);


$installdefs = array (
  'id' => 'LegalSupport',
  'beans' => 
  array (
    0 => 
    array (
      'module' => 'legal_events',
      'class' => 'legal_events',
      'path' => 'modules/legal_events/legal_events.php',
      'tab' => true,
    ),
    1 => 
    array (
      'module' => 'legal_arrestees',
      'class' => 'legal_arrestees',
      'path' => 'modules/legal_arrestees/legal_arrestees.php',
      'tab' => true,
    ),
    2 => 
    array (
      'module' => 'legal_witnesses',
      'class' => 'legal_witnesses',
      'path' => 'modules/legal_witnesses/legal_witnesses.php',
      'tab' => true,
    ),
    3 => 
    array (
      'module' => 'legal_evidence',
      'class' => 'legal_evidence',
      'path' => 'modules/legal_evidence/legal_evidence.php',
      'tab' => true,
    ),
    4 => 
    array (
      'module' => 'legal_lawyers',
      'class' => 'legal_lawyers',
      'path' => 'modules/legal_lawyers/legal_lawyers.php',
      'tab' => true,
    ),
    5 => 
    array (
      'module' => 'legal_charges',
      'class' => 'legal_charges',
      'path' => 'modules/legal_charges/legal_charges.php',
      'tab' => true,
    ),
  ),
  'layoutdefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/legal_events_legal_evidence_legal_evidence.php',
      'to_module' => 'legal_evidence',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/legal_events_legal_evidence_legal_events.php',
      'to_module' => 'legal_events',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/legal_events_legal_witnesses_legal_witnesses.php',
      'to_module' => 'legal_witnesses',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/legal_events_legal_witnesses_legal_events.php',
      'to_module' => 'legal_events',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/legal_arrestees_legal_events_legal_events.php',
      'to_module' => 'legal_events',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/legal_arrestees_legal_events_legal_arrestees.php',
      'to_module' => 'legal_arrestees',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/legal_arrestees_legal_evidence_legal_evidence.php',
      'to_module' => 'legal_evidence',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/legal_arrestees_legal_evidence_legal_arrestees.php',
      'to_module' => 'legal_arrestees',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/legal_arrestees_legal_witnesses_legal_witnesses.php',
      'to_module' => 'legal_witnesses',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/legal_arrestees_legal_witnesses_legal_arrestees.php',
      'to_module' => 'legal_arrestees',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/legal_arrestees_legal_charges_legal_charges.php',
      'to_module' => 'legal_charges',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/layoutdefs/legal_arrestees_legal_charges_legal_arrestees.php',
      'to_module' => 'legal_arrestees',
    ),
  ),
  'relationships' => 
  array (
    0 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/legal_events_legal_evidenceMetaData.php',
    ),
    1 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/legal_events_legal_witnessesMetaData.php',
    ),
    2 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/legal_arrestees_legal_eventsMetaData.php',
    ),
    3 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/legal_arrestees_legal_evidenceMetaData.php',
    ),
    4 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/legal_arrestees_legal_witnessesMetaData.php',
    ),
    5 => 
    array (
      'meta_data' => '<basepath>/SugarModules/relationships/relationships/legal_arrestees_legal_chargesMetaData.php',
    ),
  ),
  'image_dir' => '<basepath>/icons',
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_events',
      'to' => 'modules/legal_events',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_arrestees',
      'to' => 'modules/legal_arrestees',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_witnesses',
      'to' => 'modules/legal_witnesses',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_evidence',
      'to' => 'modules/legal_evidence',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_lawyers',
      'to' => 'modules/legal_lawyers',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_charges',
      'to' => 'modules/legal_charges',
    ),
  ),
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/legal_evidence.php',
      'to_module' => 'legal_evidence',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/legal_evidence.php',
      'to_module' => 'legal_evidence',
      'language' => 'es_es',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/legal_evidence.php',
      'to_module' => 'legal_evidence',
      'language' => 'ru_ru',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/legal_events.php',
      'to_module' => 'legal_events',
      'language' => 'en_us',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/legal_events.php',
      'to_module' => 'legal_events',
      'language' => 'es_es',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/legal_events.php',
      'to_module' => 'legal_events',
      'language' => 'ru_ru',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/legal_witnesses.php',
      'to_module' => 'legal_witnesses',
      'language' => 'en_us',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/legal_witnesses.php',
      'to_module' => 'legal_witnesses',
      'language' => 'es_es',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/legal_witnesses.php',
      'to_module' => 'legal_witnesses',
      'language' => 'ru_ru',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/legal_events.php',
      'to_module' => 'legal_events',
      'language' => 'en_us',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/legal_events.php',
      'to_module' => 'legal_events',
      'language' => 'es_es',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/legal_events.php',
      'to_module' => 'legal_events',
      'language' => 'ru_ru',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/legal_events.php',
      'to_module' => 'legal_events',
      'language' => 'en_us',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/legal_events.php',
      'to_module' => 'legal_events',
      'language' => 'es_es',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/legal_events.php',
      'to_module' => 'legal_events',
      'language' => 'ru_ru',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/legal_arrestees.php',
      'to_module' => 'legal_arrestees',
      'language' => 'en_us',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/legal_arrestees.php',
      'to_module' => 'legal_arrestees',
      'language' => 'es_es',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/legal_arrestees.php',
      'to_module' => 'legal_arrestees',
      'language' => 'ru_ru',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/legal_evidence.php',
      'to_module' => 'legal_evidence',
      'language' => 'en_us',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/legal_evidence.php',
      'to_module' => 'legal_evidence',
      'language' => 'es_es',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/legal_evidence.php',
      'to_module' => 'legal_evidence',
      'language' => 'ru_ru',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/legal_arrestees.php',
      'to_module' => 'legal_arrestees',
      'language' => 'en_us',
    ),
    22 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/legal_arrestees.php',
      'to_module' => 'legal_arrestees',
      'language' => 'es_es',
    ),
    23 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/legal_arrestees.php',
      'to_module' => 'legal_arrestees',
      'language' => 'ru_ru',
    ),
    24 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/legal_witnesses.php',
      'to_module' => 'legal_witnesses',
      'language' => 'en_us',
    ),
    25 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/legal_witnesses.php',
      'to_module' => 'legal_witnesses',
      'language' => 'es_es',
    ),
    26 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/legal_witnesses.php',
      'to_module' => 'legal_witnesses',
      'language' => 'ru_ru',
    ),
    27 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/legal_arrestees.php',
      'to_module' => 'legal_arrestees',
      'language' => 'en_us',
    ),
    28 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/legal_arrestees.php',
      'to_module' => 'legal_arrestees',
      'language' => 'es_es',
    ),
    29 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/legal_arrestees.php',
      'to_module' => 'legal_arrestees',
      'language' => 'ru_ru',
    ),
    30 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/legal_charges.php',
      'to_module' => 'legal_charges',
      'language' => 'en_us',
    ),
    31 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/legal_charges.php',
      'to_module' => 'legal_charges',
      'language' => 'es_es',
    ),
    32 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/legal_charges.php',
      'to_module' => 'legal_charges',
      'language' => 'ru_ru',
    ),
    33 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/legal_arrestees.php',
      'to_module' => 'legal_arrestees',
      'language' => 'en_us',
    ),
    34 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/legal_arrestees.php',
      'to_module' => 'legal_arrestees',
      'language' => 'es_es',
    ),
    35 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/language/legal_arrestees.php',
      'to_module' => 'legal_arrestees',
      'language' => 'ru_ru',
    ),
    36 => 
    array (
      'from' => '<basepath>/SugarModules/language/application/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
  ),
  'vardefs' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/legal_events_legal_evidence_legal_evidence.php',
      'to_module' => 'legal_evidence',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/legal_events_legal_evidence_legal_events.php',
      'to_module' => 'legal_events',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/legal_events_legal_witnesses_legal_witnesses.php',
      'to_module' => 'legal_witnesses',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/legal_events_legal_witnesses_legal_events.php',
      'to_module' => 'legal_events',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/legal_arrestees_legal_events_legal_events.php',
      'to_module' => 'legal_events',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/legal_arrestees_legal_events_legal_arrestees.php',
      'to_module' => 'legal_arrestees',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/legal_arrestees_legal_evidence_legal_evidence.php',
      'to_module' => 'legal_evidence',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/legal_arrestees_legal_evidence_legal_arrestees.php',
      'to_module' => 'legal_arrestees',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/legal_arrestees_legal_witnesses_legal_witnesses.php',
      'to_module' => 'legal_witnesses',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/legal_arrestees_legal_witnesses_legal_arrestees.php',
      'to_module' => 'legal_arrestees',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/legal_arrestees_legal_charges_legal_charges.php',
      'to_module' => 'legal_charges',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/relationships/vardefs/legal_arrestees_legal_charges_legal_arrestees.php',
      'to_module' => 'legal_arrestees',
    ),
  ),
);