	<?php
/*********************************************************************************
 * SugarCRM is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004 - 2007 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

	$manifest = array (
		 'acceptable_sugar_versions' => 
		  array (
	     	'5.0.0e'
		  ),
		  'acceptable_sugar_flavors' =>
		  array(
		  	'CE', 'PRO','ENT'
		  ),
		  'readme'=>'',
		  'key'=>'',
		  'author' => '',
		  'description' => '',
		  'icon' => '',
		  'is_uninstallable' => true,
		  'name' => 'Memory Hole Customizations',
		  'published_date' => '2014-12-12 00:21:50',
		  'type' => 'module',
		  'version' => '1418343710',
		  'remove_tables' => 'prompt',
		  );
$installdefs = array (
  'id' => 'Memory Hole Customizations',
  'language' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/include/language/en_us.lang.php',
      'to_module' => 'application',
      'language' => 'en_us',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_arrestees/language/en_us.lang.php',
      'to_module' => 'legal_arrestees',
      'language' => 'en_us',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_events/language/en_us.lang.php',
      'to_module' => 'legal_events',
      'language' => 'en_us',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_evidence/language/en_us.lang.php',
      'to_module' => 'legal_evidence',
      'language' => 'en_us',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_lawyers/language/en_us.lang.php',
      'to_module' => 'legal_lawyers',
      'language' => 'en_us',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_witnesses/language/en_us.lang.php',
      'to_module' => 'legal_witnesses',
      'language' => 'en_us',
    ),
  ),
  'custom_fields' => 
  array (
    'legal_arresteesarrest_time_c' => 
    array (
      'id' => 'legal_arresteesarrest_time_c',
      'name' => 'arrest_time_c',
      'label' => 'LBL_ARREST_TIME',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'varchar',
      'max_size' => '25',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2008-06-07 11:23:58',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteesdisposition_c' => 
    array (
      'id' => 'legal_arresteesdisposition_c',
      'name' => 'disposition_c',
      'label' => 'LBL_DISPOSITION',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'enum',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => 'open',
      'date_modified' => '2011-12-19 21:01:46',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '1',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => 'disposition_list',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteesrelease_type_c' => 
    array (
      'id' => 'legal_arresteesrelease_type_c',
      'name' => 'release_type_c',
      'label' => 'LBL_RELEASE_TYPE',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'enum',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => 'in',
      'date_modified' => '2008-06-11 21:31:54',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => 'release_type_list',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteesgender_id_c' => 
    array (
      'id' => 'legal_arresteesgender_id_c',
      'name' => 'gender_id_c',
      'label' => 'LBL_GENDER_ID',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'enum',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2008-06-09 04:57:44',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => 'gender_list',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteesstate_c' => 
    array (
      'id' => 'legal_arresteesstate_c',
      'name' => 'state_c',
      'label' => 'LBL_STATE',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'enum',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => 'CA',
      'date_modified' => '2009-01-14 08:09:10',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => 'states_list',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteesgender_solidarity_c' => 
    array (
      'id' => 'legal_arresteesgender_solidarity_c',
      'name' => 'gender_solidarity_c',
      'label' => 'LBL_GENDER_SOLIDARITY',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'bool',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '0',
      'date_modified' => '2008-09-02 10:54:53',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteeswants_lawyer_c' => 
    array (
      'id' => 'legal_arresteeswants_lawyer_c',
      'name' => 'wants_lawyer_c',
      'label' => 'LBL_WANTS_LAWYER',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'bool',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '0',
      'date_modified' => '2008-08-29 11:45:32',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteeswants_bail_c' => 
    array (
      'id' => 'legal_arresteeswants_bail_c',
      'name' => 'wants_bail_c',
      'label' => 'LBL_WANTS_BAIL',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'bool',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '0',
      'date_modified' => '2008-08-29 11:45:58',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteesfirst_appearance_date_c' => 
    array (
      'id' => 'legal_arresteesfirst_appearance_date_c',
      'name' => 'first_appearance_date_c',
      'label' => 'LBL_FIRST_APPEARANCE_DATE',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'date',
      'max_size' => NULL,
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2009-01-14 09:06:33',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteesfirst_appearance_location_c' => 
    array (
      'id' => 'legal_arresteesfirst_appearance_location_c',
      'name' => 'first_appearance_location_c',
      'label' => 'LBL_FIRST_APPEARANCE_LOCATION',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'varchar',
      'max_size' => '25',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2014-12-11 05:03:32',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteessupport_person_c' => 
    array (
      'id' => 'legal_arresteessupport_person_c',
      'name' => 'support_person_c',
      'label' => 'LBL_SUPPORT_PERSON',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'varchar',
      'max_size' => '25',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2008-08-29 11:55:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteessupport_contact_c' => 
    array (
      'id' => 'legal_arresteessupport_contact_c',
      'name' => 'support_contact_c',
      'label' => 'LBL_SUPPORT_CONTACT',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'varchar',
      'max_size' => '25',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2008-08-29 11:56:03',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteeslegal_strategy_c' => 
    array (
      'id' => 'legal_arresteeslegal_strategy_c',
      'name' => 'legal_strategy_c',
      'label' => 'LBL_LEGAL_STRATEGY',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'text',
      'max_size' => NULL,
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2009-02-12 21:11:45',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteesmedical_needs_c' => 
    array (
      'id' => 'legal_arresteesmedical_needs_c',
      'name' => 'medical_needs_c',
      'label' => 'LBL_MEDICAL_NEEDS',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'text',
      'max_size' => NULL,
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2008-09-01 06:47:04',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteesjail_location_c' => 
    array (
      'id' => 'legal_arresteesjail_location_c',
      'name' => 'jail_location_c',
      'label' => 'LBL_JAIL_LOCATION',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'varchar',
      'max_size' => '25',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2008-09-01 06:47:36',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteesbooking_number_c' => 
    array (
      'id' => 'legal_arresteesbooking_number_c',
      'name' => 'booking_number_c',
      'label' => 'LBL_BOOKING_NUMBER',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'varchar',
      'max_size' => '25',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2014-12-11 05:04:27',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteesjail_facility_c' => 
    array (
      'id' => 'legal_arresteesjail_facility_c',
      'name' => 'jail_facility_c',
      'label' => 'LBL_JAIL_FACILITY',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'varchar',
      'max_size' => '25',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2008-09-01 06:48:08',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteesaffinity_group_c' => 
    array (
      'id' => 'legal_arresteesaffinity_group_c',
      'name' => 'affinity_group_c',
      'label' => 'LBL_AFFINITY_GROUP',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'varchar',
      'max_size' => '25',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2008-09-01 06:48:31',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteescontacts_c' => 
    array (
      'id' => 'legal_arresteescontacts_c',
      'name' => 'contacts_c',
      'label' => 'LBL_CONTACTS',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'text',
      'max_size' => NULL,
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2008-09-01 06:48:54',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteessupport_needs_c' => 
    array (
      'id' => 'legal_arresteessupport_needs_c',
      'name' => 'support_needs_c',
      'label' => 'LBL_SUPPORT_NEEDS',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'text',
      'max_size' => NULL,
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2009-01-14 09:08:52',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteesunconfirmed_arrest_c' => 
    array (
      'id' => 'legal_arresteesunconfirmed_arrest_c',
      'name' => 'unconfirmed_arrest_c',
      'label' => 'LBL_UNCONFIRMED_ARREST',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'bool',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '0',
      'date_modified' => '2008-09-02 10:56:26',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteesmedical_concern_c' => 
    array (
      'id' => 'legal_arresteesmedical_concern_c',
      'name' => 'medical_concern_c',
      'label' => 'LBL_MEDICAL_CONCERN',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'bool',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '0',
      'date_modified' => '2008-09-02 10:56:44',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteescharges_c' => 
    array (
      'id' => 'legal_arresteescharges_c',
      'name' => 'charges_c',
      'label' => 'LBL_CHARGES',
      'comments' => 'To add new charge, go to Admin -&gt; Dropdown Editor -&gt; charges_list and add the new charge in the left pane.',
      'help' => 'To add new charge, go to Admin -&gt; Dropdown Editor -&gt; charges_list and add the new charge in the left pane.',
      'module' => 'legal_arrestees',
      'type' => 'multienum',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '-blank-',
      'date_modified' => '2014-12-11 05:03:49',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => 'charges_list',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteesbail_c' => 
    array (
      'id' => 'legal_arresteesbail_c',
      'name' => 'bail_c',
      'label' => 'LBL_BAIL',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'varchar',
      'max_size' => '25',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2009-01-14 09:09:09',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteescase_number_c' => 
    array (
      'id' => 'legal_arresteescase_number_c',
      'name' => 'case_number_c',
      'label' => 'LBL_CASE_NUMBER',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'varchar',
      'max_size' => '35',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2008-09-06 02:50:57',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteesnext_hearing_time_c' => 
    array (
      'id' => 'legal_arresteesnext_hearing_time_c',
      'name' => 'next_hearing_time_c',
      'label' => 'LBL_NEXT_HEARING_TIME',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'varchar',
      'max_size' => '200',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2008-09-17 15:44:13',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteesjurisdiction_c' => 
    array (
      'id' => 'legal_arresteesjurisdiction_c',
      'name' => 'jurisdiction_c',
      'label' => 'LBL_JURISDICTION',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'enum',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '-blank-',
      'date_modified' => '2014-12-11 05:04:12',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '1',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => 'jursidiction_list',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteescaseid_c' => 
    array (
      'id' => 'legal_arresteescaseid_c',
      'name' => 'caseid_c',
      'label' => 'LBL_CASEID',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'varchar',
      'max_size' => '40',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2008-09-12 23:54:22',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteesproperty_issues_c' => 
    array (
      'id' => 'legal_arresteesproperty_issues_c',
      'name' => 'property_issues_c',
      'label' => 'LBL_PROPERTY_ISSUES',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'text',
      'max_size' => NULL,
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2009-02-10 03:01:18',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteespolice_report_number_c' => 
    array (
      'id' => 'legal_arresteespolice_report_number_c',
      'name' => 'police_report_number_c',
      'label' => 'LBL_POLICE_REPORT_NUMBER',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'varchar',
      'max_size' => '25',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2010-03-06 21:22:39',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteesinfraction_c' => 
    array (
      'id' => 'legal_arresteesinfraction_c',
      'name' => 'infraction_c',
      'label' => 'LBL_INFRACTION',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'bool',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '0',
      'date_modified' => '2010-04-08 05:36:20',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteesmisdemeanors_c' => 
    array (
      'id' => 'legal_arresteesmisdemeanors_c',
      'name' => 'misdemeanors_c',
      'label' => 'LBL_MISDEMEANORS',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'bool',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '0',
      'date_modified' => '2010-04-08 05:36:44',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteesdropped_c' => 
    array (
      'id' => 'legal_arresteesdropped_c',
      'name' => 'dropped_c',
      'label' => 'LBL_DROPPED',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'bool',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '0',
      'date_modified' => '2010-04-08 05:56:10',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteesdocket_c' => 
    array (
      'id' => 'legal_arresteesdocket_c',
      'name' => 'docket_c',
      'label' => 'LBL_DOCKET',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'varchar',
      'max_size' => '25',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2014-12-11 05:02:45',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteesconfirmed_info_c' => 
    array (
      'id' => 'legal_arresteesconfirmed_info_c',
      'name' => 'confirmed_info_c',
      'label' => 'LBL_CONFIRMED_INFO',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'date',
      'max_size' => NULL,
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2011-05-17 01:05:10',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteesinfo_notes_c' => 
    array (
      'id' => 'legal_arresteesinfo_notes_c',
      'name' => 'info_notes_c',
      'label' => 'LBL_INFO_NOTES',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'varchar',
      'max_size' => '100',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2014-12-11 05:02:51',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteesemail_bounce_c' => 
    array (
      'id' => 'legal_arresteesemail_bounce_c',
      'name' => 'email_bounce_c',
      'label' => 'LBL_EMAIL_BOUNCE',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'bool',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '0',
      'date_modified' => '2011-05-17 01:06:14',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteesbad_phone_c' => 
    array (
      'id' => 'legal_arresteesbad_phone_c',
      'name' => 'bad_phone_c',
      'label' => 'LBL_BAD_PHONE',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'bool',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '0',
      'date_modified' => '2011-05-17 01:07:03',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteeslistserv_c' => 
    array (
      'id' => 'legal_arresteeslistserv_c',
      'name' => 'listserv_c',
      'label' => 'LBL_LISTSERV',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'bool',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '0',
      'date_modified' => '2011-05-17 01:37:14',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteesarrest_city_c' => 
    array (
      'id' => 'legal_arresteesarrest_city_c',
      'name' => 'arrest_city_c',
      'label' => 'LBL_ARREST_CITY',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'enum',
      'max_size' => '255',
      'require_option' => '1',
      'default_value' => '-blank-',
      'date_modified' => '2014-12-11 05:07:09',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '1',
      'duplicate_merge' => '1',
      'reportable' => '0',
      'ext1' => 'arrest_city_list',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_arresteesstay_away_c' => 
    array (
      'id' => 'legal_arresteesstay_away_c',
      'name' => 'stay_away_c',
      'label' => 'LBL_STAY_AWAY',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_arrestees',
      'type' => 'bool',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '0',
      'date_modified' => '2012-02-09 00:16:08',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_eventsmass_arrest_c' => 
    array (
      'id' => 'legal_eventsmass_arrest_c',
      'name' => 'mass_arrest_c',
      'label' => 'LBL_MASS_ARREST',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_events',
      'type' => 'bool',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '0',
      'date_modified' => '2008-10-30 00:34:27',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_evidenceevidence_id_c' => 
    array (
      'id' => 'legal_evidenceevidence_id_c',
      'name' => 'evidence_id_c',
      'label' => 'LBL_EVIDENCE_ID',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_evidence',
      'type' => 'varchar',
      'max_size' => '40',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2008-08-20 17:49:47',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_evidencedatetimelocation_c' => 
    array (
      'id' => 'legal_evidencedatetimelocation_c',
      'name' => 'datetimelocation_c',
      'label' => 'LBL_DATETIMELOCATION',
      'comments' => 'One Date/Time/Location per line, with date in MM/DD format and time in 24 hour fomat, like this: 8/29 | 15:21 | 14th and Broadway',
      'help' => 'One Date/Time/Location per line, with date in MM/DD format and time in 24 hour fomat, like this: 8/29 | 15:21 | 14th and Broadway',
      'module' => 'legal_evidence',
      'type' => 'text',
      'max_size' => NULL,
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2008-08-20 18:03:48',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_evidenceuse_of_force_c' => 
    array (
      'id' => 'legal_evidenceuse_of_force_c',
      'name' => 'use_of_force_c',
      'label' => 'LBL_USE_OF_FORCE',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_evidence',
      'type' => 'multienum',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2008-08-23 02:43:26',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => 'useofforce_list',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_lawyersorganization_c' => 
    array (
      'id' => 'legal_lawyersorganization_c',
      'name' => 'organization_c',
      'label' => 'LBL_ORGANIZATION',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_lawyers',
      'type' => 'varchar',
      'max_size' => '60',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2008-06-07 12:49:01',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_lawyersnlg_c' => 
    array (
      'id' => 'legal_lawyersnlg_c',
      'name' => 'nlg_c',
      'label' => 'LBL_NLG',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_lawyers',
      'type' => 'bool',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '0',
      'date_modified' => '2011-12-29 22:48:55',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_lawyersstate_c' => 
    array (
      'id' => 'legal_lawyersstate_c',
      'name' => 'state_c',
      'label' => 'LBL_STATE',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_lawyers',
      'type' => 'enum',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => 'MN',
      'date_modified' => '2008-06-11 10:50:03',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => 'states_list',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_lawyerslawyer_roles_c' => 
    array (
      'id' => 'legal_lawyerslawyer_roles_c',
      'name' => 'lawyer_roles_c',
      'label' => 'LBL_LAWYER_ROLES',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_lawyers',
      'type' => 'multienum',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2008-08-20 18:15:10',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => 'lawyers_roles_list',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_lawyerslawyersspecialties_c' => 
    array (
      'id' => 'legal_lawyerslawyersspecialties_c',
      'name' => 'lawyersspecialties_c',
      'label' => 'LBL_LAWYERSSPECIALTIES',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_lawyers',
      'type' => 'multienum',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2008-08-20 19:07:50',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => 'lawyer_specialties_list',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_lawyerslicense_number_c' => 
    array (
      'id' => 'legal_lawyerslicense_number_c',
      'name' => 'license_number_c',
      'label' => 'LBL_LICENSE_NUMBER',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_lawyers',
      'type' => 'varchar',
      'max_size' => '25',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2008-09-01 06:16:07',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_lawyerspracticing_states_c' => 
    array (
      'id' => 'legal_lawyerspracticing_states_c',
      'name' => 'practicing_states_c',
      'label' => 'LBL_PRACTICING_STATES',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_lawyers',
      'type' => 'varchar',
      'max_size' => '25',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2008-09-01 06:16:44',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_lawyersyears_in_practice_c' => 
    array (
      'id' => 'legal_lawyersyears_in_practice_c',
      'name' => 'years_in_practice_c',
      'label' => 'LBL_YEARS_IN_PRACTICE',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_lawyers',
      'type' => 'int',
      'max_size' => '11',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2008-09-01 06:17:24',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_lawyersyears_in_crim_practice_c' => 
    array (
      'id' => 'legal_lawyersyears_in_crim_practice_c',
      'name' => 'years_in_crim_practice_c',
      'label' => 'LBL_YEARS_IN_CRIM_PRACTICE',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_lawyers',
      'type' => 'int',
      'max_size' => '11',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2008-09-01 06:17:52',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_lawyerscan_represent_in_mn_c' => 
    array (
      'id' => 'legal_lawyerscan_represent_in_mn_c',
      'name' => 'can_represent_in_mn_c',
      'label' => 'LBL_CAN_REPRESENT_IN_MN',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_lawyers',
      'type' => 'bool',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '0',
      'date_modified' => '2008-09-01 06:18:31',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_lawyersfederal_practice_c' => 
    array (
      'id' => 'legal_lawyersfederal_practice_c',
      'name' => 'federal_practice_c',
      'label' => 'LBL_FEDERAL_PRACTICE',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_lawyers',
      'type' => 'bool',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '0',
      'date_modified' => '2008-09-01 06:19:37',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_lawyersrepresented_protestors_c' => 
    array (
      'id' => 'legal_lawyersrepresented_protestors_c',
      'name' => 'represented_protestors_c',
      'label' => 'LBL_REPRESENTED_PROTESTORS',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_lawyers',
      'type' => 'bool',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '0',
      'date_modified' => '2008-09-01 06:20:20',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_lawyerscivil_rights_experience_c' => 
    array (
      'id' => 'legal_lawyerscivil_rights_experience_c',
      'name' => 'civil_rights_experience_c',
      'label' => 'LBL_CIVIL_RIGHTS_EXPERIENCE',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_lawyers',
      'type' => 'bool',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '0',
      'date_modified' => '2008-09-01 06:21:49',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_lawyersregular_courts_c' => 
    array (
      'id' => 'legal_lawyersregular_courts_c',
      'name' => 'regular_courts_c',
      'label' => 'LBL_REGULAR_COURTS',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_lawyers',
      'type' => 'varchar',
      'max_size' => '25',
      'require_option' => '0',
      'default_value' => NULL,
      'date_modified' => '2008-09-01 06:22:26',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_lawyerspublic_defender_c' => 
    array (
      'id' => 'legal_lawyerspublic_defender_c',
      'name' => 'public_defender_c',
      'label' => 'LBL_PUBLIC_DEFENDER',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_lawyers',
      'type' => 'bool',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => '0',
      'date_modified' => '2008-11-04 20:59:35',
      'deleted' => '0',
      'audited' => '0',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => NULL,
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
    'legal_witnessesstate_c' => 
    array (
      'id' => 'legal_witnessesstate_c',
      'name' => 'state_c',
      'label' => 'LBL_STATE',
      'comments' => NULL,
      'help' => NULL,
      'module' => 'legal_witnesses',
      'type' => 'enum',
      'max_size' => '255',
      'require_option' => '0',
      'default_value' => 'MN',
      'date_modified' => '2008-06-11 10:50:37',
      'deleted' => '0',
      'audited' => '1',
      'mass_update' => '0',
      'duplicate_merge' => '0',
      'reportable' => '0',
      'ext1' => 'states_list',
      'ext2' => NULL,
      'ext3' => NULL,
      'ext4' => NULL,
    ),
  ),
  'copy' => 
  array (
    0 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_arrestees/metadata/detailviewdefs.php',
      'to' => 'custom/modules/legal_arrestees/metadata/detailviewdefs.php',
    ),
    1 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_arrestees/metadata/detailviewdefs.php',
      'to' => 'custom/working/modules/legal_arrestees/metadata/detailviewdefs.php',
    ),
    2 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_arrestees/metadata/editviewdefs.php',
      'to' => 'custom/modules/legal_arrestees/metadata/editviewdefs.php',
    ),
    3 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_arrestees/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/legal_arrestees/metadata/editviewdefs.php',
    ),
    4 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_arrestees/metadata/searchdefs.php',
      'to' => 'custom/modules/legal_arrestees/metadata/searchdefs.php',
    ),
    5 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_arrestees/metadata/searchdefs.php',
      'to' => 'custom/working/modules/legal_arrestees/metadata/searchdefs.php',
    ),
    6 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_arrestees/metadata/listviewdefs.php',
      'to' => 'custom/modules/legal_arrestees/metadata/listviewdefs.php',
    ),
    7 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_charges/metadata/editviewdefs.php',
      'to' => 'custom/modules/legal_charges/metadata/editviewdefs.php',
    ),
    8 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_charges/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/legal_charges/metadata/editviewdefs.php',
    ),
    9 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_charges/metadata/searchdefs.php',
      'to' => 'custom/modules/legal_charges/metadata/searchdefs.php',
    ),
    10 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_charges/metadata/searchdefs.php',
      'to' => 'custom/working/modules/legal_charges/metadata/searchdefs.php',
    ),
    11 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_charges/metadata/listviewdefs.php',
      'to' => 'custom/modules/legal_charges/metadata/listviewdefs.php',
    ),
    12 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_events/metadata/editviewdefs.php',
      'to' => 'custom/modules/legal_events/metadata/editviewdefs.php',
    ),
    13 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_events/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/legal_events/metadata/editviewdefs.php',
    ),
    14 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_events/metadata/searchdefs.php',
      'to' => 'custom/modules/legal_events/metadata/searchdefs.php',
    ),
    15 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_events/metadata/searchdefs.php',
      'to' => 'custom/working/modules/legal_events/metadata/searchdefs.php',
    ),
    16 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_events/metadata/listviewdefs.php',
      'to' => 'custom/modules/legal_events/metadata/listviewdefs.php',
    ),
    17 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_evidence/metadata/editviewdefs.php',
      'to' => 'custom/modules/legal_evidence/metadata/editviewdefs.php',
    ),
    18 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_evidence/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/legal_evidence/metadata/editviewdefs.php',
    ),
    19 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_evidence/metadata/searchdefs.php',
      'to' => 'custom/modules/legal_evidence/metadata/searchdefs.php',
    ),
    20 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_evidence/metadata/searchdefs.php',
      'to' => 'custom/working/modules/legal_evidence/metadata/searchdefs.php',
    ),
    21 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_evidence/metadata/listviewdefs.php',
      'to' => 'custom/modules/legal_evidence/metadata/listviewdefs.php',
    ),
    22 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_lawyers/metadata/editviewdefs.php',
      'to' => 'custom/modules/legal_lawyers/metadata/editviewdefs.php',
    ),
    23 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_lawyers/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/legal_lawyers/metadata/editviewdefs.php',
    ),
    24 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_lawyers/metadata/searchdefs.php',
      'to' => 'custom/modules/legal_lawyers/metadata/searchdefs.php',
    ),
    25 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_lawyers/metadata/searchdefs.php',
      'to' => 'custom/working/modules/legal_lawyers/metadata/searchdefs.php',
    ),
    26 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_lawyers/metadata/listviewdefs.php',
      'to' => 'custom/modules/legal_lawyers/metadata/listviewdefs.php',
    ),
    27 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_witnesses/metadata/editviewdefs.php',
      'to' => 'custom/modules/legal_witnesses/metadata/editviewdefs.php',
    ),
    28 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_witnesses/metadata/editviewdefs.php',
      'to' => 'custom/working/modules/legal_witnesses/metadata/editviewdefs.php',
    ),
    29 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_witnesses/metadata/searchdefs.php',
      'to' => 'custom/modules/legal_witnesses/metadata/searchdefs.php',
    ),
    30 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_witnesses/metadata/searchdefs.php',
      'to' => 'custom/working/modules/legal_witnesses/metadata/searchdefs.php',
    ),
    31 => 
    array (
      'from' => '<basepath>/SugarModules/modules/legal_witnesses/metadata/listviewdefs.php',
      'to' => 'custom/modules/legal_witnesses/metadata/listviewdefs.php',
    ),
  ),
);